---
title: "Doxycyline effect"
author: "Michael Smallegan\n"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output: github_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(stringsAsFactors = FALSE,
        dplyr.summarise.inform = FALSE,
        tidyverse.quiet = TRUE)
library(tidyverse)
library(DESeq2)
library(seriation)
source("../util/_plot_theme.R")
source("../util/_util.R")
source("../util/deseq.R")
source("../util/figures.R")
source("../util/")
source("../01_setup/assumptions.R")

if(!file.exists("data")) dir.create("data")
if(!file.exists("results")) dir.create("results")
if(!file.exists("figures")) dir.create("figures")

# Keep track of thresholds for figure naming
thresh <- paste0("pval", pval_thresh, "_l2fc", round(l2fc_thresh, 2))
```

```{r load, include=FALSE}
load("../01_setup/results/rnaseq_data.RData",
     verbose = TRUE)
  
rnaseq_samples <- rnaseq_samples %>%
  filter(date_sequenced != "2018-09")
samples <- samples %>%
  filter(date_sequenced != "2018-09")
```

### EC KO long timecourse dox effect

```{r run-deseq-esc-ko-control}
if(!file.exists("results/esc_ko_control_long.RData")) {
  source("../util/deseq.R")
  esc_ko_control_long <- deseq_vs_zero(ct = "ESC", 
                                       tc_len = "long", 
                                       fko = "KO", 
                                       fi = "control")
  save(esc_ko_control_long, file = "results/esc_ko_control_long.RData")
}

load("results/esc_ko_control_long.RData", verbose = T)
```

```{r sig-deseq-esc-ko-control}
esc_ko_control_long <- esc_ko_control_long %>%
  mutate(sig = padj <= pval_thresh & max_abs_l2fc_shrunken > l2fc_thresh)

esc_ko_control_long_sig <- esc_ko_control_long %>% 
  filter(sig == TRUE)
```

```{r lfcplot-deseq-esc-ko-control}
make_timecourse_lfc_plot(deseq_res = esc_ko_control_long,
                         genes_to_include = unique(esc_ko_control_long_sig$gene_id),
                         y_lim = c(-5.5,8.2),
                         draw_plot = FALSE)
ggsave(paste0("figures/esc_ko_control_long_lfc_", thresh, ".pdf"), 
       height = 3, width = 3.5, useDingbats = FALSE)
```

### ESC KO short timecourse dox effect

```{r}
if(!file.exists("results/esc_ko_control_short.RData")) {
  source("../util/deseq.R")
  esc_ko_control_short <- deseq_vs_zero(ct = "ESC", 
                                       tc_len = "short", 
                                       fko = "KO", 
                                       fi = "control")
  save(esc_ko_control_short, file = "results/esc_ko_control_short.RData")
}

load("results/esc_ko_control_short.RData", verbose = T)
```

```{r}
esc_ko_control_short <- esc_ko_control_short %>%
  mutate(sig = padj <= pval_thresh & max_abs_l2fc_shrunken > l2fc_thresh)

esc_ko_control_short_sig <- esc_ko_control_short %>% 
  filter(sig == TRUE)
```

```{r}
make_timecourse_lfc_plot(deseq_res = esc_ko_control_short,
                         genes_to_include = unique(esc_ko_control_short_sig$gene_id),
                         draw_plot = FALSE)
ggsave(paste0("figures/esc_ko_control_short_lfc_", thresh, ".pdf"), 
       height = 3, width = 3.5, useDingbats = FALSE)
```

### ESC WT long timecourse dox effect

```{r}
if(!file.exists("results/esc_wt_control_long.RData")) {
  source("../util/deseq.R")
  esc_wt_control_long <- deseq_vs_zero(ct = "ESC", 
                                       tc_len = "long", 
                                       fko = "WT", 
                                       fi = "control")
  save(esc_wt_control_long, file = "results/esc_wt_control_long.RData")
}

load("results/esc_wt_control_long.RData", verbose = T)
```

```{r}
esc_wt_control_long <- esc_wt_control_long %>%
  mutate(sig = padj <= pval_thresh & max_abs_l2fc_shrunken > l2fc_thresh)

esc_wt_control_long_sig <- esc_wt_control_long %>% 
  filter(sig == TRUE)
```

```{r}
make_timecourse_lfc_plot(deseq_res = esc_wt_control_long,
                         genes_to_include = unique(esc_wt_control_long_sig$gene_id),
                         y_lim = c(-5,5),
                         draw_plot = FALSE)
ggsave(paste0("figures/esc_wt_control_long_lfc_", thresh, ".pdf"), 
       height = 3, width = 3.5, useDingbats = FALSE)
```

### ESC WT Short timecourse dox effect

```{r}
if(!file.exists("results/esc_wt_control_short.RData")) {
  source("../util/deseq.R")
  esc_wt_control_short <- deseq_vs_zero(ct = "ESC", 
                                       tc_len = "short", 
                                       fko = "WT", 
                                       fi = "control")
  save(esc_wt_control_short, file = "results/esc_wt_control_short.RData")
}

load("results/esc_wt_control_short.RData", verbose = T)
```

```{r}
esc_wt_control_short <- esc_wt_control_short %>%
  mutate(sig = padj <= pval_thresh & max_abs_l2fc_shrunken > l2fc_thresh)

esc_wt_control_short_sig <- esc_wt_control_short %>% 
  filter(sig == TRUE)
```

```{r}
make_timecourse_lfc_plot(deseq_res = esc_wt_control_short,
                         genes_to_include = unique(esc_wt_control_short_sig$gene_id),
                         draw_plot = FALSE)
ggsave(paste0("figures/esc_wt_control_short_lfc_", thresh, ".pdf"), 
       height = 3, width = 3.5, useDingbats = FALSE)
```

### NPC KO Short timecourse dox effect

```{r}
if(!file.exists("results/npc_ko_control_short.RData")) {
  source("../util/deseq.R")
  npc_ko_control_short <- deseq_vs_zero(ct = "NPC", 
                                       tc_len = "short", 
                                       fko = "KO", 
                                       fi = "control")
  save(npc_ko_control_short, file = "results/npc_ko_control_short.RData")
}

load("results/npc_ko_control_short.RData", verbose = T)
```

```{r}
npc_ko_control_short <- npc_ko_control_short %>%
  mutate(sig = padj <= pval_thresh & max_abs_l2fc_shrunken > l2fc_thresh)

npc_ko_control_short_sig <- npc_ko_control_short %>% 
  filter(sig == TRUE)
```

There are no significant genes for NPC KO control.

### NPC WT Short timecourse dox effect

```{r}
if(!file.exists("results/npc_wt_control_short.RData")) {
  source("../util/deseq.R")
  npc_wt_control_short <- deseq_vs_zero(ct = "NPC", 
                                       tc_len = "short", 
                                       fko = "WT", 
                                       fi = "control")
  save(npc_wt_control_short, file = "results/npc_wt_control_short.RData")
}

load("results/npc_wt_control_short.RData", verbose = T)
```

```{r}
npc_wt_control_short <- npc_wt_control_short %>%
  mutate(sig = padj <= pval_thresh & max_abs_l2fc_shrunken > l2fc_thresh)

npc_wt_control_short_sig <- npc_wt_control_short %>% 
  filter(sig == TRUE)
```

```{r}
make_timecourse_lfc_plot(deseq_res = npc_wt_control_short,
                         genes_to_include = unique(npc_wt_control_short_sig$gene_id),
                         draw_plot = FALSE)
ggsave(paste0("figures/npc_wt_control_short_lfc_", thresh, ".pdf"), 
       height = 3, width = 3.5, useDingbats = FALSE)
```

