#!/bin/bash
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2708_read1.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_OE_control_0min_dox_rep1_read1.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2710_read1.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_OE_control_0min_dox_rep2_read1.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2707_read1.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_OE_control_0min_dox_rep3_read1.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2762_read1.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_OE_control_720min_dox_rep1_read1.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2765_read1.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_OE_control_720min_dox_rep2_read1.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2758_read1.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_OE_control_720min_dox_rep3_read1.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2741_read1.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_OE_control_1440min_dox_rep1_read1.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2732_read1.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_OE_control_1440min_dox_rep2_read1.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2730_read1.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_OE_control_1440min_dox_rep3_read1.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2731_read1.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_OE_control_2880min_dox_rep1_read1.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2738_read1.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_OE_control_2880min_dox_rep2_read1.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2737_read1.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_OE_control_2880min_dox_rep3_read1.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2715_read1.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_OE_control_5760min_dox_rep1_read1.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2706_read1.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_OE_control_5760min_dox_rep2_read1.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2716_read1.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_OE_control_5760min_dox_rep3_read1.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2711_read1.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_OE_firre_induced_0min_dox_rep1_read1.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2717_read1.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_OE_firre_induced_0min_dox_rep2_read1.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2714_read1.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_OE_firre_induced_0min_dox_rep3_read1.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2755_read1.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_OE_firre_induced_720min_dox_rep1_read1.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2760_read1.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_OE_firre_induced_720min_dox_rep2_read1.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2759_read1.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_OE_firre_induced_720min_dox_rep3_read1.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2735_read1.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_OE_firre_induced_1440min_dox_rep1_read1.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2736_read1.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_OE_firre_induced_1440min_dox_rep2_read1.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2740_read1.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_OE_firre_induced_1440min_dox_rep3_read1.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2733_read1.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_OE_firre_induced_2880min_dox_rep1_read1.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2739_read1.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_OE_firre_induced_2880min_dox_rep2_read1.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2734_read1.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_OE_firre_induced_2880min_dox_rep3_read1.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2712_read1.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_OE_firre_induced_5760min_dox_rep1_read1.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2713_read1.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_OE_firre_induced_5760min_dox_rep2_read1.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2709_read1.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_OE_firre_induced_5760min_dox_rep3_read1.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2536_read1.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_OE_control_0min_dox_rep1_read1.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2520_read1.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_OE_control_0min_dox_rep2_read1.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2529_read1.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_OE_control_30min_dox_rep1_read1.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2533_read1.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_OE_control_30min_dox_rep2_read1.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2519_read1.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_OE_control_60min_dox_rep1_read1.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2537_read1.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_OE_control_60min_dox_rep2_read1.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2526_read1.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_OE_control_90min_dox_rep1_read1.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2518_read1.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_OE_control_90min_dox_rep2_read1.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2521_read1.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_OE_control_120min_dox_rep1_read1.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2525_read1.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_OE_control_120min_dox_rep2_read1.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2531_read1.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_OE_control_150min_dox_rep1_read1.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2528_read1.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_OE_control_150min_dox_rep2_read1.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2530_read1.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_OE_control_180min_dox_rep1_read1.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2522_read1.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_OE_control_180min_dox_rep2_read1.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2524_read1.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_OE_control_210min_dox_rep1_read1.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2539_read1.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_OE_control_210min_dox_rep2_read1.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2516_read1.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_OE_control_240min_dox_rep1_read1.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2538_read1.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_OE_control_240min_dox_rep2_read1.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2517_read1.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_OE_control_270min_dox_rep1_read1.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2523_read1.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_OE_control_270min_dox_rep2_read1.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2532_read1.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_OE_control_300min_dox_rep1_read1.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2527_read1.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_OE_control_300min_dox_rep2_read1.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2535_read1.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_OE_control_330min_dox_rep1_read1.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2534_read1.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_OE_control_330min_dox_rep2_read1.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2563_read1.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_OE_firre_induced_0min_dox_rep1_read1.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2551_read1.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_OE_firre_induced_0min_dox_rep2_read1.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2556_read1.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_OE_firre_induced_30min_dox_rep1_read1.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2548_read1.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_OE_firre_induced_30min_dox_rep2_read1.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2546_read1.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_OE_firre_induced_60min_dox_rep1_read1.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2557_read1.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_OE_firre_induced_60min_dox_rep2_read1.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2555_read1.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_OE_firre_induced_90min_dox_rep1_read1.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2550_read1.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_OE_firre_induced_90min_dox_rep2_read1.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2561_read1.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_OE_firre_induced_120min_dox_rep1_read1.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2543_read1.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_OE_firre_induced_120min_dox_rep2_read1.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2544_read1.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_OE_firre_induced_150min_dox_rep1_read1.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2549_read1.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_OE_firre_induced_150min_dox_rep2_read1.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2540_read1.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_OE_firre_induced_180min_dox_rep1_read1.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2560_read1.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_OE_firre_induced_180min_dox_rep2_read1.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2545_read1.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_OE_firre_induced_210min_dox_rep1_read1.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2552_read1.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_OE_firre_induced_210min_dox_rep2_read1.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2558_read1.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_OE_firre_induced_240min_dox_rep1_read1.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2554_read1.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_OE_firre_induced_240min_dox_rep2_read1.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2559_read1.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_OE_firre_induced_270min_dox_rep1_read1.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2562_read1.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_OE_firre_induced_270min_dox_rep2_read1.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2541_read1.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_OE_firre_induced_300min_dox_rep1_read1.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2542_read1.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_OE_firre_induced_300min_dox_rep2_read1.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2547_read1.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_OE_firre_induced_330min_dox_rep1_read1.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2553_read1.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_OE_firre_induced_330min_dox_rep2_read1.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2727_read1.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_Rescue_control_0min_dox_rep1_read1.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2722_read1.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_Rescue_control_0min_dox_rep2_read1.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2720_read1.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_Rescue_control_0min_dox_rep3_read1.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2756_read1.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_Rescue_control_720min_dox_rep1_read1.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2763_read1.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_Rescue_control_720min_dox_rep2_read1.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2764_read1.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_Rescue_control_720min_dox_rep3_read1.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2749_read1.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_Rescue_control_1440min_dox_rep1_read1.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2751_read1.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_Rescue_control_1440min_dox_rep2_read1.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2745_read1.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_Rescue_control_1440min_dox_rep3_read1.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2750_read1.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_Rescue_control_2880min_dox_rep1_read1.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2752_read1.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_Rescue_control_2880min_dox_rep2_read1.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2753_read1.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_Rescue_control_2880min_dox_rep3_read1.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2721_read1.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_Rescue_control_5760min_dox_rep1_read1.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2728_read1.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_Rescue_control_5760min_dox_rep2_read1.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2719_read1.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_Rescue_control_5760min_dox_rep3_read1.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2726_read1.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_Rescue_firre_induced_0min_dox_rep1_read1.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2724_read1.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_Rescue_firre_induced_0min_dox_rep2_read1.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2723_read1.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_Rescue_firre_induced_0min_dox_rep3_read1.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2761_read1.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_Rescue_firre_induced_720min_dox_rep1_read1.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2754_read1.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_Rescue_firre_induced_720min_dox_rep2_read1.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2757_read1.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_Rescue_firre_induced_720min_dox_rep3_read1.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2746_read1.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_Rescue_firre_induced_1440min_dox_rep1_read1.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2748_read1.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_Rescue_firre_induced_1440min_dox_rep2_read1.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2742_read1.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_Rescue_firre_induced_1440min_dox_rep3_read1.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2747_read1.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_Rescue_firre_induced_2880min_dox_rep1_read1.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2743_read1.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_Rescue_firre_induced_2880min_dox_rep2_read1.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2744_read1.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_Rescue_firre_induced_2880min_dox_rep3_read1.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2725_read1.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_Rescue_firre_induced_5760min_dox_rep1_read1.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2718_read1.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_Rescue_firre_induced_5760min_dox_rep2_read1.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2729_read1.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_Rescue_firre_induced_5760min_dox_rep3_read1.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2420_read1.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_Rescue_control_0min_dox_rep1_read1.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2443_read1.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_Rescue_control_0min_dox_rep2_read1.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2423_read1.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_Rescue_control_30min_dox_rep1_read1.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2435_read1.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_Rescue_control_30min_dox_rep2_read1.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2419_read1.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_Rescue_control_60min_dox_rep1_read1.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2447_read1.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_Rescue_control_60min_dox_rep2_read1.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2408_read1.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_Rescue_control_90min_dox_rep1_read1.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2446_read1.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_Rescue_control_90min_dox_rep2_read1.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2422_read1.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_Rescue_control_120min_dox_rep1_read1.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2445_read1.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_Rescue_control_120min_dox_rep2_read1.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2411_read1.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_Rescue_control_150min_dox_rep1_read1.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2444_read1.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_Rescue_control_150min_dox_rep2_read1.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2409_read1.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_Rescue_control_180min_dox_rep1_read1.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2432_read1.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_Rescue_control_180min_dox_rep2_read1.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2418_read1.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_Rescue_control_210min_dox_rep1_read1.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2442_read1.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_Rescue_control_210min_dox_rep2_read1.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2407_read1.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_Rescue_control_240min_dox_rep1_read1.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2430_read1.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_Rescue_control_240min_dox_rep2_read1.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2406_read1.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_Rescue_control_270min_dox_rep1_read1.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2431_read1.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_Rescue_control_270min_dox_rep2_read1.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2421_read1.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_Rescue_control_300min_dox_rep1_read1.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2433_read1.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_Rescue_control_300min_dox_rep2_read1.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2410_read1.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_Rescue_control_330min_dox_rep1_read1.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2434_read1.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_Rescue_control_330min_dox_rep2_read1.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2415_read1.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_Rescue_firre_induced_0min_dox_rep1_read1.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2437_read1.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_Rescue_firre_induced_0min_dox_rep2_read1.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2413_read1.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_Rescue_firre_induced_30min_dox_rep1_read1.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2440_read1.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_Rescue_firre_induced_30min_dox_rep2_read1.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2427_read1.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_Rescue_firre_induced_60min_dox_rep1_read1.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2438_read1.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_Rescue_firre_induced_60min_dox_rep2_read1.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2417_read1.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_Rescue_firre_induced_90min_dox_rep1_read1.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2453_read1.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_Rescue_firre_induced_90min_dox_rep2_read1.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2416_read1.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_Rescue_firre_induced_120min_dox_rep1_read1.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2439_read1.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_Rescue_firre_induced_120min_dox_rep2_read1.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2425_read1.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_Rescue_firre_induced_150min_dox_rep1_read1.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2450_read1.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_Rescue_firre_induced_150min_dox_rep2_read1.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2429_read1.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_Rescue_firre_induced_180min_dox_rep1_read1.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2441_read1.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_Rescue_firre_induced_180min_dox_rep2_read1.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2412_read1.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_Rescue_firre_induced_210min_dox_rep1_read1.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2449_read1.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_Rescue_firre_induced_210min_dox_rep2_read1.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2426_read1.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_Rescue_firre_induced_240min_dox_rep1_read1.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2436_read1.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_Rescue_firre_induced_240min_dox_rep2_read1.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2428_read1.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_Rescue_firre_induced_270min_dox_rep1_read1.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2451_read1.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_Rescue_firre_induced_270min_dox_rep2_read1.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2424_read1.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_Rescue_firre_induced_300min_dox_rep1_read1.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2448_read1.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_Rescue_firre_induced_300min_dox_rep2_read1.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2414_read1.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_Rescue_firre_induced_330min_dox_rep1_read1.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2452_read1.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_Rescue_firre_induced_330min_dox_rep2_read1.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/atacseq/fastq/JR2772_read1.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_Rescue_control_0min_ATACseq_read1.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/atacseq/fastq/JR2773_read1.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_Rescue_control_30min_ATACseq_read1.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/atacseq/fastq/JR2774_read1.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_Rescue_control_60min_ATACseq_read1.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/atacseq/fastq/JR2784_read1.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_Rescue_control_90min_ATACseq_read1.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/atacseq/fastq/JR2785_read1.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_Rescue_control_120min_ATACseq_read1.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/atacseq/fastq/JR2786_read1.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_Rescue_control_150min_ATACseq_read1.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/atacseq/fastq/JR2775_read1.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_Rescue_firre_induced_0min_ATACseq_read1.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/atacseq/fastq/JR2776_read1.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_Rescue_firre_induced_30min_ATACseq_read1.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/atacseq/fastq/JR2777_read1.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_Rescue_firre_induced_60min_ATACseq_read1.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/atacseq/fastq/JR2787_read1.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_Rescue_firre_induced_90min_ATACseq_read1.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/atacseq/fastq/JR2788_read1.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_Rescue_firre_induced_120min_ATACseq_read1.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/atacseq/fastq/JR2789_read1.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_Rescue_firre_induced_150min_ATACseq_read1.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/atacseq/fastq/JR2766_read1.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_OE_control_0min_ATACseq_read1.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/atacseq/fastq/JR2767_read1.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_OE_control_30min_ATACseq_read1.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/atacseq/fastq/JR2768_read1.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_OE_control_60min_ATACseq_read1.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/atacseq/fastq/JR2778_read1.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_OE_control_90min_ATACseq_read1.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/atacseq/fastq/JR2779_read1.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_OE_control_120min_ATACseq_read1.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/atacseq/fastq/JR2780_read1.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_OE_control_150min_ATACseq_read1.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/atacseq/fastq/JR2769_read1.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_OE_firre_induced_0min_ATACseq_read1.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/atacseq/fastq/JR2770_read1.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_OE_firre_induced_30min_ATACseq_read1.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/atacseq/fastq/JR2771_read1.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_OE_firre_induced_60min_ATACseq_read1.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/atacseq/fastq/JR2781_read1.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_OE_firre_induced_90min_ATACseq_read1.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/atacseq/fastq/JR2782_read1.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_OE_firre_induced_120min_ATACseq_read1.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/atacseq/fastq/JR2783_read1.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_OE_firre_induced_150min_ATACseq_read1.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2708_read2.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_OE_control_0min_dox_rep1_read2.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2710_read2.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_OE_control_0min_dox_rep2_read2.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2707_read2.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_OE_control_0min_dox_rep3_read2.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2762_read2.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_OE_control_720min_dox_rep1_read2.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2765_read2.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_OE_control_720min_dox_rep2_read2.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2758_read2.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_OE_control_720min_dox_rep3_read2.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2741_read2.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_OE_control_1440min_dox_rep1_read2.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2732_read2.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_OE_control_1440min_dox_rep2_read2.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2730_read2.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_OE_control_1440min_dox_rep3_read2.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2731_read2.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_OE_control_2880min_dox_rep1_read2.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2738_read2.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_OE_control_2880min_dox_rep2_read2.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2737_read2.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_OE_control_2880min_dox_rep3_read2.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2715_read2.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_OE_control_5760min_dox_rep1_read2.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2706_read2.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_OE_control_5760min_dox_rep2_read2.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2716_read2.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_OE_control_5760min_dox_rep3_read2.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2711_read2.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_OE_firre_induced_0min_dox_rep1_read2.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2717_read2.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_OE_firre_induced_0min_dox_rep2_read2.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2714_read2.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_OE_firre_induced_0min_dox_rep3_read2.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2755_read2.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_OE_firre_induced_720min_dox_rep1_read2.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2760_read2.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_OE_firre_induced_720min_dox_rep2_read2.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2759_read2.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_OE_firre_induced_720min_dox_rep3_read2.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2735_read2.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_OE_firre_induced_1440min_dox_rep1_read2.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2736_read2.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_OE_firre_induced_1440min_dox_rep2_read2.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2740_read2.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_OE_firre_induced_1440min_dox_rep3_read2.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2733_read2.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_OE_firre_induced_2880min_dox_rep1_read2.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2739_read2.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_OE_firre_induced_2880min_dox_rep2_read2.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2734_read2.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_OE_firre_induced_2880min_dox_rep3_read2.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2712_read2.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_OE_firre_induced_5760min_dox_rep1_read2.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2713_read2.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_OE_firre_induced_5760min_dox_rep2_read2.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2709_read2.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_OE_firre_induced_5760min_dox_rep3_read2.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2536_read2.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_OE_control_0min_dox_rep1_read2.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2520_read2.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_OE_control_0min_dox_rep2_read2.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2529_read2.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_OE_control_30min_dox_rep1_read2.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2533_read2.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_OE_control_30min_dox_rep2_read2.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2519_read2.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_OE_control_60min_dox_rep1_read2.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2537_read2.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_OE_control_60min_dox_rep2_read2.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2526_read2.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_OE_control_90min_dox_rep1_read2.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2518_read2.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_OE_control_90min_dox_rep2_read2.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2521_read2.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_OE_control_120min_dox_rep1_read2.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2525_read2.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_OE_control_120min_dox_rep2_read2.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2531_read2.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_OE_control_150min_dox_rep1_read2.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2528_read2.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_OE_control_150min_dox_rep2_read2.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2530_read2.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_OE_control_180min_dox_rep1_read2.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2522_read2.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_OE_control_180min_dox_rep2_read2.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2524_read2.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_OE_control_210min_dox_rep1_read2.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2539_read2.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_OE_control_210min_dox_rep2_read2.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2516_read2.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_OE_control_240min_dox_rep1_read2.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2538_read2.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_OE_control_240min_dox_rep2_read2.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2517_read2.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_OE_control_270min_dox_rep1_read2.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2523_read2.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_OE_control_270min_dox_rep2_read2.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2532_read2.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_OE_control_300min_dox_rep1_read2.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2527_read2.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_OE_control_300min_dox_rep2_read2.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2535_read2.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_OE_control_330min_dox_rep1_read2.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2534_read2.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_OE_control_330min_dox_rep2_read2.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2563_read2.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_OE_firre_induced_0min_dox_rep1_read2.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2551_read2.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_OE_firre_induced_0min_dox_rep2_read2.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2556_read2.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_OE_firre_induced_30min_dox_rep1_read2.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2548_read2.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_OE_firre_induced_30min_dox_rep2_read2.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2546_read2.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_OE_firre_induced_60min_dox_rep1_read2.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2557_read2.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_OE_firre_induced_60min_dox_rep2_read2.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2555_read2.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_OE_firre_induced_90min_dox_rep1_read2.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2550_read2.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_OE_firre_induced_90min_dox_rep2_read2.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2561_read2.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_OE_firre_induced_120min_dox_rep1_read2.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2543_read2.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_OE_firre_induced_120min_dox_rep2_read2.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2544_read2.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_OE_firre_induced_150min_dox_rep1_read2.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2549_read2.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_OE_firre_induced_150min_dox_rep2_read2.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2540_read2.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_OE_firre_induced_180min_dox_rep1_read2.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2560_read2.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_OE_firre_induced_180min_dox_rep2_read2.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2545_read2.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_OE_firre_induced_210min_dox_rep1_read2.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2552_read2.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_OE_firre_induced_210min_dox_rep2_read2.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2558_read2.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_OE_firre_induced_240min_dox_rep1_read2.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2554_read2.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_OE_firre_induced_240min_dox_rep2_read2.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2559_read2.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_OE_firre_induced_270min_dox_rep1_read2.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2562_read2.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_OE_firre_induced_270min_dox_rep2_read2.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2541_read2.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_OE_firre_induced_300min_dox_rep1_read2.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2542_read2.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_OE_firre_induced_300min_dox_rep2_read2.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2547_read2.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_OE_firre_induced_330min_dox_rep1_read2.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2553_read2.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_OE_firre_induced_330min_dox_rep2_read2.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2727_read2.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_Rescue_control_0min_dox_rep1_read2.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2722_read2.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_Rescue_control_0min_dox_rep2_read2.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2720_read2.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_Rescue_control_0min_dox_rep3_read2.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2756_read2.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_Rescue_control_720min_dox_rep1_read2.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2763_read2.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_Rescue_control_720min_dox_rep2_read2.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2764_read2.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_Rescue_control_720min_dox_rep3_read2.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2749_read2.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_Rescue_control_1440min_dox_rep1_read2.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2751_read2.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_Rescue_control_1440min_dox_rep2_read2.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2745_read2.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_Rescue_control_1440min_dox_rep3_read2.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2750_read2.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_Rescue_control_2880min_dox_rep1_read2.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2752_read2.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_Rescue_control_2880min_dox_rep2_read2.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2753_read2.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_Rescue_control_2880min_dox_rep3_read2.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2721_read2.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_Rescue_control_5760min_dox_rep1_read2.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2728_read2.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_Rescue_control_5760min_dox_rep2_read2.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2719_read2.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_Rescue_control_5760min_dox_rep3_read2.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2726_read2.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_Rescue_firre_induced_0min_dox_rep1_read2.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2724_read2.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_Rescue_firre_induced_0min_dox_rep2_read2.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2723_read2.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_Rescue_firre_induced_0min_dox_rep3_read2.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2761_read2.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_Rescue_firre_induced_720min_dox_rep1_read2.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2754_read2.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_Rescue_firre_induced_720min_dox_rep2_read2.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2757_read2.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_Rescue_firre_induced_720min_dox_rep3_read2.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2746_read2.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_Rescue_firre_induced_1440min_dox_rep1_read2.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2748_read2.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_Rescue_firre_induced_1440min_dox_rep2_read2.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2742_read2.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_Rescue_firre_induced_1440min_dox_rep3_read2.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2747_read2.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_Rescue_firre_induced_2880min_dox_rep1_read2.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2743_read2.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_Rescue_firre_induced_2880min_dox_rep2_read2.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2744_read2.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_Rescue_firre_induced_2880min_dox_rep3_read2.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2725_read2.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_Rescue_firre_induced_5760min_dox_rep1_read2.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2718_read2.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_Rescue_firre_induced_5760min_dox_rep2_read2.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2729_read2.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_Rescue_firre_induced_5760min_dox_rep3_read2.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2420_read2.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_Rescue_control_0min_dox_rep1_read2.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2443_read2.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_Rescue_control_0min_dox_rep2_read2.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2423_read2.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_Rescue_control_30min_dox_rep1_read2.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2435_read2.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_Rescue_control_30min_dox_rep2_read2.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2419_read2.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_Rescue_control_60min_dox_rep1_read2.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2447_read2.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_Rescue_control_60min_dox_rep2_read2.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2408_read2.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_Rescue_control_90min_dox_rep1_read2.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2446_read2.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_Rescue_control_90min_dox_rep2_read2.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2422_read2.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_Rescue_control_120min_dox_rep1_read2.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2445_read2.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_Rescue_control_120min_dox_rep2_read2.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2411_read2.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_Rescue_control_150min_dox_rep1_read2.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2444_read2.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_Rescue_control_150min_dox_rep2_read2.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2409_read2.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_Rescue_control_180min_dox_rep1_read2.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2432_read2.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_Rescue_control_180min_dox_rep2_read2.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2418_read2.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_Rescue_control_210min_dox_rep1_read2.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2442_read2.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_Rescue_control_210min_dox_rep2_read2.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2407_read2.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_Rescue_control_240min_dox_rep1_read2.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2430_read2.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_Rescue_control_240min_dox_rep2_read2.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2406_read2.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_Rescue_control_270min_dox_rep1_read2.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2431_read2.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_Rescue_control_270min_dox_rep2_read2.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2421_read2.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_Rescue_control_300min_dox_rep1_read2.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2433_read2.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_Rescue_control_300min_dox_rep2_read2.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2410_read2.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_Rescue_control_330min_dox_rep1_read2.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2434_read2.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_Rescue_control_330min_dox_rep2_read2.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2415_read2.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_Rescue_firre_induced_0min_dox_rep1_read2.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2437_read2.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_Rescue_firre_induced_0min_dox_rep2_read2.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2413_read2.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_Rescue_firre_induced_30min_dox_rep1_read2.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2440_read2.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_Rescue_firre_induced_30min_dox_rep2_read2.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2427_read2.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_Rescue_firre_induced_60min_dox_rep1_read2.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2438_read2.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_Rescue_firre_induced_60min_dox_rep2_read2.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2417_read2.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_Rescue_firre_induced_90min_dox_rep1_read2.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2453_read2.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_Rescue_firre_induced_90min_dox_rep2_read2.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2416_read2.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_Rescue_firre_induced_120min_dox_rep1_read2.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2439_read2.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_Rescue_firre_induced_120min_dox_rep2_read2.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2425_read2.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_Rescue_firre_induced_150min_dox_rep1_read2.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2450_read2.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_Rescue_firre_induced_150min_dox_rep2_read2.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2429_read2.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_Rescue_firre_induced_180min_dox_rep1_read2.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2441_read2.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_Rescue_firre_induced_180min_dox_rep2_read2.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2412_read2.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_Rescue_firre_induced_210min_dox_rep1_read2.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2449_read2.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_Rescue_firre_induced_210min_dox_rep2_read2.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2426_read2.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_Rescue_firre_induced_240min_dox_rep1_read2.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2436_read2.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_Rescue_firre_induced_240min_dox_rep2_read2.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2428_read2.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_Rescue_firre_induced_270min_dox_rep1_read2.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2451_read2.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_Rescue_firre_induced_270min_dox_rep2_read2.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2424_read2.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_Rescue_firre_induced_300min_dox_rep1_read2.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2448_read2.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_Rescue_firre_induced_300min_dox_rep2_read2.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2414_read2.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_Rescue_firre_induced_330min_dox_rep1_read2.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/rnaseq/fastq/JR2452_read2.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_Rescue_firre_induced_330min_dox_rep2_read2.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/atacseq/fastq/JR2772_read2.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_Rescue_control_0min_ATACseq_read2.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/atacseq/fastq/JR2773_read2.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_Rescue_control_30min_ATACseq_read2.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/atacseq/fastq/JR2774_read2.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_Rescue_control_60min_ATACseq_read2.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/atacseq/fastq/JR2784_read2.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_Rescue_control_90min_ATACseq_read2.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/atacseq/fastq/JR2785_read2.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_Rescue_control_120min_ATACseq_read2.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/atacseq/fastq/JR2786_read2.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_Rescue_control_150min_ATACseq_read2.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/atacseq/fastq/JR2775_read2.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_Rescue_firre_induced_0min_ATACseq_read2.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/atacseq/fastq/JR2776_read2.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_Rescue_firre_induced_30min_ATACseq_read2.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/atacseq/fastq/JR2777_read2.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_Rescue_firre_induced_60min_ATACseq_read2.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/atacseq/fastq/JR2787_read2.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_Rescue_firre_induced_90min_ATACseq_read2.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/atacseq/fastq/JR2788_read2.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_Rescue_firre_induced_120min_ATACseq_read2.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/atacseq/fastq/JR2789_read2.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_Rescue_firre_induced_150min_ATACseq_read2.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/atacseq/fastq/JR2766_read2.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_OE_control_0min_ATACseq_read2.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/atacseq/fastq/JR2767_read2.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_OE_control_30min_ATACseq_read2.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/atacseq/fastq/JR2768_read2.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_OE_control_60min_ATACseq_read2.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/atacseq/fastq/JR2778_read2.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_OE_control_90min_ATACseq_read2.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/atacseq/fastq/JR2779_read2.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_OE_control_120min_ATACseq_read2.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/atacseq/fastq/JR2780_read2.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_OE_control_150min_ATACseq_read2.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/atacseq/fastq/JR2769_read2.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_OE_firre_induced_0min_ATACseq_read2.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/atacseq/fastq/JR2770_read2.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_OE_firre_induced_30min_ATACseq_read2.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/atacseq/fastq/JR2771_read2.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_OE_firre_induced_60min_ATACseq_read2.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/atacseq/fastq/JR2781_read2.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_OE_firre_induced_90min_ATACseq_read2.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/atacseq/fastq/JR2782_read2.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_OE_firre_induced_120min_ATACseq_read2.fastq.gz
mv /scratch/Shares/rinn/Michael/firre_timecourse/atacseq/fastq/JR2783_read2.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/mESC_Firre_OE_firre_induced_150min_ATACseq_read2.fastq.gz
