---
title: "Rank aggregation"
author: "Michael Smallegan"
date: "9/2/2019"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r}
options(stringsAsFactors = FALSE)
library(RobustRankAggreg); library(tidyverse)
```

```{r}
# let's create a glist out of the data we have here. 
# I think it would be logical to use the absolute shrunken logfc as the metric.
# damn, okay we need to take out the dox only samples
kodat <- read.csv("../combined_shrunken_lfc_results.csv")
kodat <- kodat[which(!grepl("dxz4", kodat$contrast)),]
dat <- kodat
dat$abslfc <- abs(dat$log2FoldChange)
dat <- dat %>% group_by(contrast) %>%
  arrange(-abslfc)

# okay, we need to merge this 
tpm_andergassen <- read.csv("results/andergassen_tpm.csv")
tpm_lewandowski <- read.csv("results/lewandowski_tpm.csv")

stopifnot(all(tpm_andergassen$gene_id == tpm_lewandowski$gene_id))
tpm_all <- merge(tpm_andergassen, tpm_lewandowski)

mean_tpm <- data.frame("gene_id" = tpm_all$gene_id,
                       "mean_tpm" = rowMeans(tpm_all %>% select(-1) %>% as.matrix()))


dat <- merge(dat, mean_tpm)


# now let's filter out those genes with tpm < 1
dat <- dat %>% filter(mean_tpm > 1)

# hmm, let's just do this with a for loop.
# let's just make sure this is sorted properly
dat <- dat %>% arrange(-abslfc)

cts <- unique(dat$contrast)
glist <- list()
dat$gene_id
for(i in 1:length(cts)) {
  glist <- c(glist, list(dat[which(dat$contrast == cts[[i]]), "gene_id"]))
  names(glist)[length(glist)] <- cts[[i]]
}
# let's see how long it takes with just two lists of all genes
r = rankMatrix(glist, full = TRUE)
ag_list <- aggregateRanks(rmat = r, method = "RRA")
load("../gene2symbol.RData")
names(ag_list)
names(g2s)

names(ag_list)[1] <- "geneID"
ag_list <- merge(ag_list, g2s)
ag_list <- ag_list %>% arrange(Score)
# now without the timecourse data.
# actually let's just add in teh 90 minute time points. 
# that way they're represented, but not overwhelming the data. 

# let's save this data
# write.csv(ag_list, "results/rank_aggreg_tissue_data.csv", row.names = F)


source("../_setup.R")
# now let's plot it. 
# how about let's take the top 20?
topag <- ag_list[1:20,]
topag <- topag %>% arrange(-Score)
topag$geneName <- factor(topag$geneName, levels = topag$geneName)
g <- ggplot(topag, aes(x = geneName, y = -log10(Score)))
g + geom_bar(stat =  "identity") + 
  coord_flip() + ggtitle("Rank aggregation: Lewand + Anderg + TC")
ggsave("rankag_tissues.pdf")


# https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3278763/
```