#!/bin/bash
mv JR3113_R1.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/geo_submission_proseq_oct18/mESC_Firre_Rescue_firre_induced_0min_dox_rep1_PROseq_read1.fastq.gz
mv JR3114_R1.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/geo_submission_proseq_oct18/mESC_Firre_Rescue_firre_induced_15min_dox_rep1_PROseq_read1.fastq.gz
mv JR3115_R1.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/geo_submission_proseq_oct18/mESC_Firre_Rescue_firre_induced_30min_dox_rep1_PROseq_read1.fastq.gz
mv JR3116_R1.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/geo_submission_proseq_oct18/mESC_Firre_Rescue_firre_induced_0min_rep2_PROseq_read1.fastq.gz
mv JR3117_R1.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/geo_submission_proseq_oct18/mESC_Firre_Rescue_firre_induced_15min_dox_rep2_PROseq_read1.fastq.gz
mv JR3118_R1.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/geo_submission_proseq_oct18/mESC_Firre_Rescue_firre_induced_30min_dox_rep2_PROseq_read1.fastq.gz
mv JR3119_R1.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/geo_submission_proseq_oct18/mESC_Firre_Rescue_firre_induced_0min_dox_rep3_PROseq_read1.fastq.gz
mv JR3120_R1.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/geo_submission_proseq_oct18/mESC_Firre_Rescue_firre_induced_15min_dox_rep3_PROseq_read1.fastq.gz
mv JR3121_R1.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/geo_submission_proseq_oct18/mESC_Firre_Rescue_firre_induced_30min_dox_rep3_PROseq_read1.fastq.gz
mv JR3113_R2.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/geo_submission_proseq_oct18/mESC_Firre_Rescue_firre_induced_0min_dox_rep1_PROseq_read2.fastq.gz
mv JR3114_R2.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/geo_submission_proseq_oct18/mESC_Firre_Rescue_firre_induced_15min_dox_rep1_PROseq_read2.fastq.gz
mv JR3115_R2.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/geo_submission_proseq_oct18/mESC_Firre_Rescue_firre_induced_30min_dox_rep1_PROseq_read2.fastq.gz
mv JR3116_R2.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/geo_submission_proseq_oct18/mESC_Firre_Rescue_firre_induced_0min_rep2_PROseq_read2.fastq.gz
mv JR3117_R2.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/geo_submission_proseq_oct18/mESC_Firre_Rescue_firre_induced_15min_dox_rep2_PROseq_read2.fastq.gz
mv JR3118_R2.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/geo_submission_proseq_oct18/mESC_Firre_Rescue_firre_induced_30min_dox_rep2_PROseq_read2.fastq.gz
mv JR3119_R2.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/geo_submission_proseq_oct18/mESC_Firre_Rescue_firre_induced_0min_dox_rep3_PROseq_read2.fastq.gz
mv JR3120_R2.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/geo_submission_proseq_oct18/mESC_Firre_Rescue_firre_induced_15min_dox_rep3_PROseq_read2.fastq.gz
mv JR3121_R2.fastq.gz /scratch/Shares/rinn/Michael/firre_timecourse/geo_upload/geo_submission_proseq_oct18/mESC_Firre_Rescue_firre_induced_30min_dox_rep3_PROseq_read2.fastq.gz

