---
title: "Volcano plots for the overlap of Dox and Firre induced genes"
author: "Michael Smallegan"
date: "10/7/2019"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(stringsAsFactors = FALSE)
```

## Purpose

To have a summary visual explaning that there are many genes that change during Dox without Firre changing.

```{r}
dat <- read.csv("../timecourse_shrunken_lfc_results.csv")
# filter to dox
dat <- dat[grep("dox",dat$contrast),]
summary(dat$log2FoldChange)
dat <- dat %>% filter(!is.na(padj))
```

```{r}
cts <- unique(dat$contrast)
cts
# wt_dox/timepoint_210_vs_0
tdat <- dat %>% filter(contrast == cts[[15]])
 g <- ggplot(dat %>% filter(contrast == cts[[i]]), aes(x = log2FoldChange, y = -log10(padj)))
  g + geom_point() + 
    ggtitle(cts[[i]])

for(i in 1:length(cts)) {
  print(i)
  png(paste0(gsub("/","_",cts[[i]]), ".png"))
  g <- ggplot(dat %>% filter(contrast == cts[[i]]), aes(x = log2FoldChange, y = -log10(padj)))
  g + geom_point() + 
    ggtitle(cts[[i]])
  # ggsave(paste0(gsub("/","_",cts[[i]]), ".png"))
  dev.off()
}
```

```{r}
# Hmm, let's make a cummulative number of genes changing plot. 
dat_sig <- dat %>% filter(padj < 0.05, abs(log2FoldChange) > 0.5)
dat_sig <- dat_sig %>% separate(col = "contrast", into = c("condition", "timepoint"), remove = FALSE, sep = "/")
dat_sig$timepoint <- gsub("_vs_0","",gsub("timepoint_","",dat_sig$timepoint)) %>% as.numeric()

ko_sig <- dat_sig %>% filter(condition == "ko_dox")

tps <- seq(from = 30, to = 330, by = 30)

changing_genes <- c()
num_changing_genes <- c()
for(i in 1:length(tps)) {
  changing_genes <- unique(c(changing_genes, ko_sig[which(ko_sig$timepoint <= tps[[i]]), "gene_id"]))
  num_changing_genes <- c(num_changing_genes, length(changing_genes))
}

cum_deg <- data.frame("timepoint" = tps, cum_deg = num_changing_genes, condition = "ko_dox")

wt_sig <- dat_sig %>% filter(condition == "wt_dox")

tps <- seq(from = 30, to = 330, by = 30)

changing_genes <- c()
num_changing_genes <- c()
for(i in 1:length(tps)) {
  changing_genes <- unique(c(changing_genes, wt_sig[which(wt_sig$timepoint <= tps[[i]]), "gene_id"]))
  num_changing_genes <- c(num_changing_genes, length(changing_genes))
}

cum_deg <- bind_rows(cum_deg, data.frame("timepoint" = tps, cum_deg = num_changing_genes, condition = "wt_dox"))

g <- ggplot(cum_deg, aes(x = timepoint, y = cum_deg, color = condition))
g + geom_point() + geom_line()

```

```{r}
# Hmm, I think maybe I should look at the shared genes as well. 

wt_changing_genes <- c()
ko_changing_genes <- c()
wt_num_changing_genes <- c()
ko_num_changing_genes <- c()
shared_changing_genes <- c()
for(i in 1:length(tps)) {
  ko_changing_genes <- unique(c(ko_changing_genes, ko_sig[which(ko_sig$timepoint <= tps[[i]]), "gene_id"]))
  wt_changing_genes <- unique(c(wt_changing_genes, wt_sig[which(wt_sig$timepoint <= tps[[i]]), "gene_id"]))
  shared_genes <- ko_changing_genes[which(ko_changing_genes %in% wt_changing_genes)]
  ko_num_changing_genes <- c(ko_num_changing_genes, length(ko_changing_genes))
  wt_num_changing_genes <- c(wt_num_changing_genes, length(wt_changing_genes))
  shared_changing_genes <- c(shared_changing_genes, length(shared_genes))
}


sg <- data.frame("timepoint" = tps, 
                 "ko_cum" = ko_num_changing_genes,
                 "wt_cum" = wt_num_changing_genes,
                 "shared_cum" = shared_changing_genes)

sgl <- sg %>% gather(key = "condition", value = "cum_deg", 2:4)

g <- ggplot(sgl, aes(x = timepoint, y = cum_deg, color = condition, shape = condition))
g + geom_point() + 
  geom_line(data = subset(sgl, condition == "ko_cum"), lty = 2) +
  geom_line(data = subset(sgl, condition != "ko_cum"), lty = 1) +
  ggtitle("Cummulative DEGs in Dox timecourse") + 
  scale_x_continuous(breaks = tps) + 
  scale_color_manual(values = c("#7F7F7F","#EC1C24", "#7F7F7F")) +
   theme(axis.text.x = element_text(angle = 45, vjust = 1),
        text = element_text(family = "Helvetica")) +
   theme(axis.line = element_line(colour = "black"),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.border = element_blank(),
    panel.background = element_blank()) +
  xlab("Time (M)") + 
  ylab("DEGs")
ggsave("mesc_dox_cummulative_deg_plot.pdf")
```


```{r}
# Damn, okay. Let's just make the MA plots. 
for(i in 1:length(cts)) {
  print(i)
  # png(paste0(gsub("/","_",cts[[i]]), "_MA.png"))
  g <- ggplot(dat %>% filter(contrast == cts[[i]]), aes(y = log2FoldChange, x = log10(baseMean)))
  g + geom_point() + 
    ggtitle(cts[[i]])
  ggsave(paste0(gsub("/","_",cts[[i]]), "_MA.png"))
  # dev.off()
}
```

Okay, I'm going to use the 240 timepoint because that one has the highest fold changes.

```{r}
tdat <- dat %>% filter(contrast == "wt_dox_shrunken/timepoint_240_vs_0")
library(ggrepel)
tdat$sig_lfc <- abs(tdat$log2FoldChange) > 0.5 & tdat$padj < 0.05
tdat$sig <-  tdat$padj < 0.05


g <- ggplot(tdat, aes(y = log2FoldChange, x = baseMean, color = sig, label = gene_name))
g + geom_hline(yintercept = 0) + 
  # geom_point(alpha = 0.5) +
  geom_point(alpha = 0.6, data = subset(tdat, sig)) +
  geom_point(alpha = 0.2, data = subset(tdat, !sig)) +
  geom_text_repel(data = subset(tdat, sig_lfc), color = "black") +
  scale_color_manual(values = c("#7F7F7F", "#EC1C24")) +
  scale_x_log10(expand = c(0,0)) +
  scale_y_continuous(limits = c(-1,1), expand = c(0,0)) +
  theme(axis.text.x = element_text(angle = 45, vjust = 1),
        text = element_text(family = "Helvetica")) +
    ggtitle("mESC WT Dox Timepoint 240_vs_0")  +
  annotation_logticks(sides = "b") 
ggsave("wt_dox_240min_MA.pdf", useDingbats=FALSE)
```

