---
title: "heatmap"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(stringsAsFactors = FALSE)
library(dichromat)
library(tidyverse); library(pheatmap); library(pals)
```

```{r}
# let's read in the tpm and make a matrix for each gene across all conditions
gene_sets <- read.csv("results/gene_sets.csv")
gene_universe <- unique(gene_sets$gene_id)
tpm <- read.csv("results/ftc_tpm.csv")

# Let's filter this down to just the genes that are changing.
tpm <- tpm[which(tpm$gene_id %in% gene_universe),]


# Read in sample info.
samples <- read.csv("../../samplesheet.csv") 

# We're not going to analyze the mESC samples. 
samples <- samples %>% filter(cell_type == "mESCs")
# Let's also get rid of the 2nd WTiTg run. 
samples <- samples %>% filter(!grepl("^A",sample_name))


# Factorize design variables
samples$firre_ko <- factor(samples$firre_ko, levels = c("WT", "KO"))

samples$timepoint <- factor(samples$timepoint, 
                            levels = c(paste0(seq(0,330,30),"m"), "0h", "12h", "24h", "48h", "96h"))

# Change from a boolean to a string
samples[which(samples$firre_induced), "firre_induced"] <- "firre_induced"
samples[which(samples$firre_induced == FALSE), "firre_induced"] <- "firre_uninduced"
samples$firre_induced <- factor(samples$firre_induced, levels = c("firre_uninduced", "firre_induced"))
```

```{r}
# now let's add in the sample info and put the columns in order
row.names(tpm) <- tpm$gene_id
tpm <- tpm %>% select(-gene_id)
tpm <- tpm %>% as.matrix()

samples <- samples %>% arrange(genotype, firre_induced, timepoint)
tpm <- tpm[, samples$sample_id]

# Let's scale the rows
cal_z_score <- function(x){
  (x - mean(x)) / sd(x)
}
 
tpm_norm <- t(apply(tpm, 1, cal_z_score))

tpm_subset <- tpm_norm[sample(1:nrow(tpm_norm),1000),]

# let's get some annotations ready
row.names(samples) <- samples$sample_id
annotation <- samples %>% select(timepoint, firre_ko, firre_induced)
levels(annotation$timepoint)
ann_colors = list(
timepoint = c("0m"= rev(pals::ocean.gray(16))[1],   
              "30m"  = rev(pals::ocean.gray(16))[2],
              "60m"  = rev(pals::ocean.gray(16))[3],
              "90m"  = rev(pals::ocean.gray(16))[4],
              "120m" = rev(pals::ocean.gray(16))[5],
              "150m" = rev(pals::ocean.gray(16))[6],
              "180m" = rev(pals::ocean.gray(16))[7],
              "210m" = rev(pals::ocean.gray(16))[8],
              "240m" = rev(pals::ocean.gray(16))[9],
              "270m" = rev(pals::ocean.gray(16))[10],
              "300m" = rev(pals::ocean.gray(16))[11],
              "330m"= rev(pals::ocean.gray(16))[12],
              "0h"   = rev(pals::ocean.gray(16))[1],
              "12h" = rev(pals::ocean.gray(16))[13],
              "24h"  = rev(pals::ocean.gray(16))[14],
              "48h"  = rev(pals::ocean.gray(16))[15],
              "96h"= rev(pals::ocean.gray(16))[16]),
  
firre_ko = c("WT" = pals::watlington(2)[1],
"KO" = pals::watlington(2)[2]),
firre_induced = c("firre_uninduced" = pals::watlington(2)[1],
                  "firre_induced" = pals::watlington(2)[2])
)

# Create a custom color ramp
orgn <- colorRampPalette(c("#284d42","#59ac94", "#ffffff", "#ffb250", "#a36717"))

# let's make a heatmap
pheatmap(tpm_subset, cluster_cols = FALSE, show_rownames = FALSE, 
         show_colnames = FALSE, cutree_rows = 5, treeheight_row = 10,
         color = orgn(100),
         breaks = seq(-4,4,length.out = 101),
         annotation_col = annotation,
         annotation_colors = ann_colors)
```

```{r}
# Hmm, it may look a little nicer if we merge the replicates.
# For this I would like to just merge the 0m timepoint with the 0h timepoint.
samples$timepoint <- as.character(samples$timepoint)
samples[which(samples$timepoint == "0h"), "timepoint"] <- "0m"

tpm_mean <- tpm %>% as.data.frame() %>%
  rownames_to_column(var = "gene_id") %>%
  gather("sample_id", "tpm", 2:ncol(.)) %>%
  merge(samples) 
tpm_mean <- tpm_mean %>% group_by(firre_ko, firre_induced, 
                                  timepoint, gene_id) %>%
  summarize(mean_tpm = mean(tpm))
tpm_mean <- tpm_mean %>% 
  select(gene_id, mean_tpm, firre_ko, firre_induced, timepoint) %>% 
  unite(col = condition, firre_ko, firre_induced, timepoint, sep = ";")
# let's create a new annotation data frame
annot <- data.frame(condition = unique(tpm_mean$condition)) %>%
  separate(col = "condition", into = c("firre_ko", "firre_induced", "timepoint"), remove = FALSE, sep = ";")
# refactorize
annot$firre_ko <- factor(annot$firre_ko, levels = c("WT", "KO"))

annot$timepoint <- factor(annot$timepoint, 
                            levels = c(paste0(seq(0,330,30),"m"), "12h", "24h", "48h", "96h"))
annot$firre_induced <- factor(annot$firre_induced, levels = c("firre_uninduced", "firre_induced"))


# now let's spread tpm mean
tpm_mean <- tpm_mean %>% spread(condition, mean_tpm)
# Let's write this 
write.csv(tpm_mean, "results/mean_tpm.csv")

row.names(tpm_mean) <- tpm_mean$gene_id
tpm_mean <- tpm_mean %>% select(-gene_id) %>%
  as.data.frame()

annot <- annot %>% 
  arrange(firre_induced, firre_ko, timepoint)

tpm_mean <- tpm_mean[,annot$condition]

tpm_norm <- t(apply(tpm_mean, 1, cal_z_score))

tpm_subset <- tpm_norm[sample(1:nrow(tpm_norm),1000),]


row.names(annot) <- annot$condition
annot <- annot %>% select(-condition)
annot <- annot %>% select(timepoint, firre_ko, firre_induced)
# let's make a heatmap
htmap <- pheatmap(tpm_norm, cluster_cols = FALSE, show_rownames = FALSE, 
         show_colnames = FALSE, treeheight_row = 10,
         color = orgn(100),
         cutree_rows = 8,
         breaks = seq(-4,4,length.out = 101),
         annotation_col = annot,
         annotation_colors = ann_colors)
# pdf("ftc_heatmap.pdf", width = 9, height = 9)
grid::grid.newpage()
grid::grid.draw(htmap$gtable)
# dev.off()
```


```{r}
library(umap)
# iris.data = iris[, grep("Sepal|Petal", colnames(iris))]
# iris.labels = iris[, "Species"]
# 
# iris.umap = umap(iris.data)
# plot.iris(iris.umap, iris.labels)
# 
# plot.iris <-  function(x, labels,
#          main="A UMAP visualization of the Iris dataset",
#          colors=c("#ff7f00", "#e377c2", "#17becf"),
#          pad=0.1, cex=0.65, pch=19, add=FALSE, legend.suffix="",
#          cex.main=1, cex.legend=1) {
# 
#   layout = x
#   if (is(x, "umap")) {
#     layout = x$layout
#   }
# 
#   xylim = range(layout)
#   xylim = xylim + ((xylim[2]-xylim[1])*pad)*c(-0.5, 0.5)
#   if (!add) {
#     par(mar=c(0.2,0.7,1.2,0.7), ps=10)
#     plot(xylim, xylim, type="n", axes=F, frame=F)
#     rect(xylim[1], xylim[1], xylim[2], xylim[2], border="#aaaaaa", lwd=0.25)
#   }
#   points(layout[,1], layout[,2], col=colors[as.integer(labels)],
#          cex=cex, pch=pch)
#   mtext(side=3, main, cex=cex.main)
# 
#   labels.u = unique(labels)
#   legend.pos = "topright"
#   legend.text = as.character(labels.u)
#   if (add) {
#     legend.pos = "bottomright"
#     legend.text = paste(as.character(labels.u), legend.suffix)
#   }
#   legend(legend.pos, legend=legend.text,
#          col=colors[as.integer(labels.u)],
#          bty="n", pch=pch, cex=cex.legend)
# }


tpm_norm <- tpm_norm %>% as.data.frame()

tpm_subset <- tpm_norm[sample(1:nrow(tpm_norm),1000),]
# tpm_mean_subset <- tpm_mean[sample(1:nrow(tpm_mean),1000),]

custom.config = umap.defaults
custom.config$random_state = 1234
custom.config$n_neighbors = 15
custom.config$n_epochs <- 250
custom.config$local_connectivity <- 0.1
custom.config$bandwidth <- 0.7
custom.config$alpha <- 1
custom.config$gamma <- 1
custom.config$spread <- 1
custom.config$set_op_mix_ratio <- 1
# help(umap.defaults)
# tpm_umap <- umap(tpm_subset, custom.config)
tpm_umap <- umap(tpm_subset)

# clustering 
kmeansfit <- kmeans(tpm_subset, 6)

umap_layout <- tpm_umap$layout
umap_layout <- data.frame("gene_id" = row.names(umap_layout),
                          "x" = umap_layout[,1],
                          "y" = umap_layout[,2])
umap_layout$firre_tg <- ""
umap_layout[which(umap_layout$gene_id %in% gene_sets[which(gene_sets$gene_set == "firre_responder_genes"),"gene_id"]), "firre_tg"] <- "firre_responder"

umap_layout$frdiff <- ""
umap_layout[which(umap_layout$gene_id %in% gene_sets[which(gene_sets$gene_set == "firre_responder_genes_diffinwtko"),"gene_id"]), "frdiff"] <- "firre_responder_diff"

# library(mclust)
# mcfit <- Mclust(tpm_subset)
umap_layout$cluster <- kmeansfit$cluster

g <- ggplot(umap_layout, aes(x = x, y = y, color = as.character(cluster)))
g + geom_point()

```


