---
title: "Doxycyline effect"
output: html_document
editor_options: 
  chunk_output_type: console
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(stringsAsFactors = FALSE,
        dplyr.summarise.inform = FALSE,
        tidyverse.quiet = TRUE)
library(tidyverse)
library(DESeq2)
library(seriation)
source("../util/_plot_theme.R")
source("../util/_util.R")
```

```{r load, include=FALSE}
load("../00_setup/results/rnaseq_data.RData")
```

```{r thresholds}
pval_thresh <- 0.05
l2fc_thresh <- log2(1.5)
```

### Long timecourse dox effect

```{r}
if(!file.exists("results/ko_dox_long.RData")) {
  
  # Filter to ESC KO long timecourse
  ko_dox_long_samples <- samples %>%
    filter(cell_type == "ESC",
           timecourse_length == "long",
           firre_ko == "KO",
           firre_induced == "control")
  ko_dox_long_counts <- salmon_gene_counts[,ko_dox_long_samples$sample_id]
  
  # Check ordering
  stopifnot(all(rownames(ko_dox_long_samples) == colnames(ko_dox_long_counts)))
  stopifnot(all(rownames(ko_dox_long_counts) == genes$gene_id))
  
  # DESeq2 -- controlling for doxycycline; likelihood ratio test
  ko_dox_long_dds <- DESeqDataSetFromMatrix(countData = ko_dox_long_counts, 
                                            colData = ko_dox_long_samples, 
                                            design = ~ timepoint)
  ko_dox_long_dds <- DESeq(ko_dox_long_dds)
  
  # Compile results
  res_names <- resultsNames(ko_dox_long_dds)
  dynamic_res <- res_names[grepl("_vs_0", res_names)]
  
  ko_dox_long_lfc <- lapply(dynamic_res, function(x) {
    results(ko_dox_long_dds, 
            name = x) %>%
      as.data.frame() %>%
      rownames_to_column("gene_id") %>% 
      merge(g2s) %>%
      mutate(result_name = x,
             timepoint = as.numeric(gsub("timepoint_|_vs_0", "", result_name)))
  }) %>% bind_rows()
  
  # Shrunken LFC results
  ko_dox_long_shrnklfc <- lapply(dynamic_res, function(x) {
    lfcShrink(ko_dox_long_dds, 
              coef = x,
              type = "apeglm") %>%
      as.data.frame() %>%
      rownames_to_column("gene_id") %>% 
      merge(g2s) %>%
      mutate(result_name = x,
             timepoint = as.numeric(gsub("timepoint_|_vs_0", "", result_name)))
  }) %>% bind_rows()
  
  # Calculate the maximum fold-change in any one timepoint
  ko_dox_long_maxfc <- ko_dox_long_shrnklfc %>%
    group_by(gene_id) %>%
    summarize(max_fc = max(abs(log2FoldChange)))
  
  ko_dox_long_shrnklfc <- ko_dox_long_shrnklfc %>%
    left_join(ko_dox_long_maxfc)
  
  save(ko_dox_long_lfc, ko_dox_long_shrnklfc, file = "results/ko_dox_long.RData")
}

load("results/ko_dox_long.RData")

ko_dox_long_shrnklfc <- ko_dox_long_shrnklfc %>%
  mutate(sig = padj <= pval_thresh & max_fc > l2fc_thresh)

ko_dox_long_sig <- ko_dox_long_shrnklfc %>% 
  filter(sig == TRUE)
```

### KO dox long dynamic genes fold-changes

```{r}
ko_dox_long_deg <- ko_dox_long_shrnklfc %>%
  filter(gene_id %in% ko_dox_long_sig$gene_id) %>%
  dplyr::select(gene_id, gene_name, baseMean, log2FoldChange, timepoint)

# Add a zero timepoint
ko_dox_long_deg_zero <- ko_dox_long_deg %>%
  dplyr::select(gene_id, gene_name, baseMean) %>%
  distinct() %>%
  mutate(log2FoldChange = 0,
         timepoint = 0) 

ko_dox_long_deg <- ko_dox_long_deg %>%
  bind_rows(ko_dox_long_deg_zero)

ko_dox_long_deg <- ko_dox_long_deg %>%
  mutate(x_adjust = scale(log10(baseMean)),
         tp_adjust = timepoint + x_adjust*20)

ko_dox_long_num_deg <- ko_dox_long_deg  %>%
  group_by(gene_id) %>%
  summarize(max_fc = log2FoldChange[which.max(abs(log2FoldChange))]) %>%
  mutate(direction = ifelse(max_fc > 0, "up", "down")) %>%
  group_by(direction) %>%
  summarize(num_deg = length(unique(gene_id)))

ggplot(ko_dox_long_deg, aes(x = tp_adjust, y = log2FoldChange, group = gene_id)) +
  geom_hline(yintercept = 0) +
  geom_line(alpha = 0.1, color = "gray70") +
  geom_point(alpha = 0.4) +
  annotate("text", x = 2880, y = -3, 
           label = paste0("n = ", ko_dox_long_num_deg %>% 
                            filter(direction == "up") %>%
                            pull(num_deg))) +
  annotate("text", x = 2880, y = 3, 
           label = paste0("n = ", ko_dox_long_num_deg %>% 
                            filter(direction == "down") %>%
                            pull(num_deg)))
ggsave("figures/ko_long_dox_lfc.pdf", height = 3, width = 3.5, useDingbats = FALSE)
```

### Short timecourse dox effect

```{r}
if(!file.exists("results/ko_dox_short.RData")) {
  
  ko_dox_short_samples <- samples %>%
    filter(cell_type == "ESC",
           timecourse_length == "short",
           firre_ko == "KO",
           firre_induced == "control")
  ko_dox_short_counts <- salmon_gene_counts[,ko_dox_short_samples$sample_id]
  
  # Check ordering
  stopifnot(all(rownames(ko_dox_short_samples) == colnames(ko_dox_short_counts)))
  stopifnot(all(rownames(ko_dox_short_counts) == genes$gene_id))
  
  # DESeq2 -- controlling for doxycycline; likelihood ratio test
  ko_dox_short_dds <- DESeqDataSetFromMatrix(countData = ko_dox_short_counts, 
                                             colData = ko_dox_short_samples, 
                                             design = ~ timepoint)
  ko_dox_short_dds <- DESeq(ko_dox_short_dds)
  
  # Compile results
  res_names <- resultsNames(ko_dox_short_dds)
  dynamic_res <- res_names[grepl("_vs_0", res_names)]
  
  ko_dox_short_lfc <- lapply(dynamic_res, function(x) {
    results(ko_dox_short_dds, 
            name = x) %>%
      as.data.frame() %>%
      rownames_to_column("gene_id") %>% 
      merge(g2s) %>%
      mutate(result_name = x,
             timepoint = as.numeric(gsub("timepoint_|_vs_0", "", result_name)))
  }) %>% bind_rows()
  
  # Shrunken LFC results
  ko_dox_short_shrnklfc <- lapply(dynamic_res, function(x) {
    lfcShrink(ko_dox_short_dds, 
              coef = x,
              type = "apeglm") %>%
      as.data.frame() %>%
      rownames_to_column("gene_id") %>% 
      merge(g2s) %>%
      mutate(result_name = x,
             timepoint = as.numeric(gsub("timepoint_|_vs_0", "", result_name)))
  }) %>% bind_rows()
  
  # Calculate the maximum fold-change in any one timepoint
  ko_dox_short_maxfc <- ko_dox_short_shrnklfc %>%
    group_by(gene_id) %>%
    summarize(max_fc = max(abs(log2FoldChange)))
  
  ko_dox_short_shrnklfc <- ko_dox_short_shrnklfc %>%
    left_join(ko_dox_short_maxfc)
  
  save(ko_dox_short_lfc, ko_dox_short_shrnklfc, file = "results/ko_dox_short.RData")
}

load("results/ko_dox_short.RData")

ko_dox_short_shrnklfc <- ko_dox_short_shrnklfc %>%
  mutate(sig = padj <= pval_thresh & max_fc > l2fc_thresh)

ko_dox_short_sig <- ko_dox_short_shrnklfc %>% 
  filter(sig == TRUE)
```

### KO dox short dynamic genes fold-changes

```{r}
ko_dox_short_deg <- ko_dox_short_shrnklfc %>%
  filter(gene_id %in% ko_dox_short_sig$gene_id) %>%
  dplyr::select(gene_id, gene_name, baseMean, log2FoldChange, timepoint)

# Add a zero timepoint
ko_dox_short_deg_zero <- ko_dox_short_deg %>%
  dplyr::select(gene_id, gene_name, baseMean) %>%
  distinct() %>%
  mutate(log2FoldChange = 0,
         timepoint = 0) 

ko_dox_short_deg <- ko_dox_short_deg %>%
  bind_rows(ko_dox_short_deg_zero)

ko_dox_short_deg <- ko_dox_short_deg %>%
  mutate(x_adjust = scale(log10(baseMean)),
         tp_adjust = timepoint + x_adjust*1)

ko_dox_short_num_deg <- ko_dox_short_deg  %>%
  group_by(gene_id) %>%
  summarize(max_fc = log2FoldChange[which.max(abs(log2FoldChange))]) %>%
  mutate(direction = ifelse(max_fc > 0, "up", "down")) %>%
  group_by(direction) %>%
  summarize(num_deg = length(unique(gene_id)))

ggplot(ko_dox_short_deg, aes(x = tp_adjust, y = log2FoldChange, group = gene_id)) +
  geom_hline(yintercept = 0) +
  geom_line(alpha = 0.1, color = "gray70") +
  geom_point(alpha = 0.5) +
  ylim(-5,5) +
  annotate("text", x = 180, y = -2, 
           label = paste0("n = ", ko_dox_short_num_deg %>% 
                            filter(direction == "up") %>%
                            pull(num_deg))) +
  annotate("text", x = 180, y = 2, 
           label = paste0("n = ", ko_dox_short_num_deg %>% 
                            filter(direction == "down") %>%
                            pull(num_deg))) +
  scale_x_continuous(breaks = c(0,60,120,180,240,300), labels = c(0,1,2,3,4,5))
ggsave("figures/ko_dox_short_lfc.pdf", height = 3, width = 3.5, useDingbats = FALSE)
```



