---
title: "Firre rescued genes"
author: "Michael Smallegan\n"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output: github_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(stringsAsFactors = FALSE)

if(!file.exists("data")) dir.create("data")
if(!file.exists("results")) dir.create("results")
if(!file.exists("figures")) dir.create("figures")
```


### Rescued genes

These are the genes that are reciprocally regulated in the KO vs WT and the Firre induced line.

```{r}
# We need the KO vs WT data
load("../04_firre_ko_vs_wt/results/wtko.RData")

wtko_res_shrnklfc <- wtko_res_shrnklfc %>%
  mutate(sig = padj <= pval_thresh & abs(log2FoldChange) > l2fc_thresh)

wtko_sig <- wtko_res_shrnklfc %>% 
  filter(sig == TRUE)

# Let's figure out which genes are rescued
rescued_genes <- wtko_sig$gene_id[wtko_sig$gene_id %in% 
                                    (ko_rescue_long_shrnklfc %>%
                                       filter(padj <= pval_thresh) %>% 
                                       pull(gene_id))]

rescue_wtko <- wtko_sig %>%
  filter(gene_id %in% rescued_genes) %>%
  dplyr::select(gene_id, gene_name, log2FoldChange) %>%
  dplyr::rename(l2fc_wtko = log2FoldChange)

rescue_ltc <- ko_rescue_long_vszero_shrnklfc %>%
  filter(gene_id %in% rescued_genes) %>%
  dplyr::select(gene_id, gene_name, log2FoldChange, timepoint) %>%
  dplyr::rename(l2fc_ltc = log2FoldChange)

rescued_df <- rescue_wtko %>%
  left_join(rescue_ltc)

rescued_df <- rescued_df %>%
  mutate(dist = abs((l2fc_wtko * -1) - l2fc_ltc))

rescued_df_closest <- rescued_df %>%
  group_by(gene_id, gene_name) %>%
  mutate(closest = min(dist) == dist,
         max_fc = max(abs(l2fc_ltc)) == abs(l2fc_ltc)) %>%
  filter(closest == TRUE)

rescued_df_closest <-  rescued_df_closest %>%
  mutate(twenty_percent = l2fc_wtko * 0.2,
         rescued = (-1*l2fc_wtko - twenty_percent)>= l2fc_ltc & l2fc_ltc>= (-1*l2fc_wtko + twenty_percent) |
           (-1*l2fc_wtko + twenty_percent)>= l2fc_ltc & l2fc_ltc>= (-1*l2fc_wtko - twenty_percent))

rescued_genes_20 <- rescued_df_closest %>% 
  filter(rescued == TRUE) %>% 
  pull(gene_name)

ggplot(rescued_df_closest, aes(x = l2fc_wtko, y = l2fc_ltc, color = rescued)) +
  geom_abline(slope = -1) +
  geom_hline(yintercept = 0) +
  geom_vline(xintercept = 0) +
  geom_point(alpha = 0.7) +
  geom_abline(slope = -0.8, lty = 2) +
  geom_abline(slope = -1.2, lty = 2) +
  xlim(-2,2) +
  ylim(-2,2)
ggsave(paste0("figures/long_rescue_lfc_scatter_", thresh, ".pdf"), 
       height = 3, width = 3, useDingbats = FALSE)


# Let's look at the number of genes overlapping between Firre responders and the KO vs WT
rescued_gene_ids_20 <- rescued_df_closest %>% 
  filter(rescued == TRUE) %>% 
  pull(gene_id)



combined_genes <- unique(c(rescued_genes, rescued_gene_ids_20))

mat <- cbind(
  rescued_genes = combined_genes %in% rescued_genes,
  reciprocal = combined_genes %in% rescued_gene_ids_20
)
fit2 <- euler(mat)


pdf("figures/rescued_vs_reciprocal_overlap.pdf", height = 2, width = 2)
plot(fit2, quantities = TRUE, fontsize = 8)
dev.off()

ggplot(rescued_df_closest, aes(x = l2fc_wtko, y = l2fc_ltc, color = rescued)) +
  geom_abline(slope = -1) +
  geom_hline(yintercept = 0) +
  geom_vline(xintercept = 0) +
  geom_point(alpha = 0.7) +
  geom_abline(slope = -0.8, lty = 2) +
  geom_abline(slope = -1.2, lty = 2) +
  xlim(-2,2) +
  ylim(-2,2)

library(ggpubr)
ggplot(rescued_df_closest %>% filter(gene_name != "Firre"), aes(x = l2fc_wtko, y = l2fc_ltc)) +
  geom_point() +
    geom_hline(yintercept = 0) +
  geom_vline(xintercept = 0) +
  stat_regline_equation(label.y = 1.5) +
  stat_cor() +
  geom_smooth(method = "lm")
ggsave(paste0("figures/long_rescue_lfc_scatter_with_linear_regression", thresh, ".pdf"), 
       height = 3, width = 3, useDingbats = FALSE)

```

```{r}
# Let's look at the number of genes overlapping between Firre responders and the KO vs WT
ko_rescue_long_sig_genes <- unique(ko_rescue_long_vszero_sig$gene_id)
wtko_sig_genes <- unique(wtko_sig$gene_id)

combined_genes <- unique(c(ko_rescue_long_sig_genes, wtko_sig_genes))

mat <- cbind(
  rescue_long = combined_genes %in% ko_rescue_long_sig_genes,
  wtko_static = combined_genes %in% wtko_sig_genes
)
fit2 <- euler(mat)

ovp <- calculate_overlap_pval(ko_rescue_long_sig_genes, wtko_sig_genes, num_measured_genes)
pdf("figures/long_timecourse_rescue_kowt_static_overlap.pdf", height = 2, width = 2)
plot(fit2, quantities = TRUE, fontsize = 8)
grid.text(paste0("P=", signif(ovp, 3)), x = 0.1, y = 0.9)
dev.off()
```

