---
title: "Firre knockout vs wildtype"
output: github_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(stringsAsFactors = FALSE,
        dplyr.summarise.inform = FALSE,
        tidyverse.quiet = TRUE)
library(tidyverse)
library(DESeq2)
library(ggrepel)
source("../util/_plot_theme.R")
source("../util/_util.R")
source("../01_setup/assumptions.R")

# Keep track of thresholds for figure naming
thresh <- paste0("pval", pval_thresh, "_l2fc", round(l2fc_thresh, 2))
```

```{r load, include=FALSE}
load("../01_setup/results/rnaseq_data.RData")
```

The cell lines derived from the mouse have had a lot of time to equilibrate to the effect of the loss of the Firre locus. This is a true static snapshot of the state of the cell without Firre.

```{r wtko}
# NOTE: The short timecourse had WT and KO cell lines
# sequenced at different times. Therefore, it is 
# Better to use the results of the long timecourse
# to compare KO vs WT.
if(!file.exists("results/wtko.RData")) {
  
  wtko_samples <- samples %>% 
    filter(cell_type == "ESC", 
           timepoint == 0, 
           timecourse_length == "long")
  
  wtko_counts <- salmon_gene_counts[,wtko_samples$sample_id]
  
  # Check the ordering
  stopifnot(all(rownames(wtko_samples) == colnames(wtko_counts)))
  stopifnot(all(rownames(wtko_counts) == genes$gene_id))
  
  # DESeq2
  wtko_dds <- DESeqDataSetFromMatrix(countData = wtko_counts, 
                                     colData = wtko_samples, 
                                     design = ~ firre_ko)
  wtko_dds <- DESeq(wtko_dds)
  
  # Results
  wtko_res_lfc <- results(wtko_dds, name = "firre_ko_KO_vs_WT") %>% 
    as.data.frame() %>%
    rownames_to_column("gene_id") %>% 
    merge(g2s) 
  
  
  wtko_res_shrnklfc <- lfcShrink(wtko_dds, coef = "firre_ko_KO_vs_WT", type = "apeglm") %>%
    as.data.frame() %>%
    rownames_to_column("gene_id") %>%
    merge(g2s)
  
  save(wtko_res_lfc, wtko_res_shrnklfc, file = "results/wtko.RData")
}


load("results/wtko.RData")

wtko_res_shrnklfc <- wtko_res_shrnklfc %>%
  mutate(sig = padj <= pval_thresh & abs(log2FoldChange) > l2fc_thresh)
write_csv(wtko_res_shrnklfc, "results/firre_ko_vs_wt_mesc_deseq_results.csv")
wtko_sig <- wtko_res_shrnklfc %>% 
  filter(sig == TRUE)
```

```{r wtko_plots}
ggplot(wtko_res_shrnklfc %>% filter(!is.na(padj)), 
       aes(x = padj)) +
  geom_histogram(bins = 30)

# Number of DEG
wtko_num_deg <- wtko_res_shrnklfc %>%
  filter(sig == TRUE) %>%
  mutate(direction = ifelse(log2FoldChange > 0, "up", "down")) %>%
  group_by(direction) %>%
  summarize(num_deg = n())

ggplot(wtko_res_shrnklfc %>% filter(!is.na(padj)), 
       aes(x = log2FoldChange, y = -log10(padj), color = sig)) +
  geom_vline(xintercept = 0) +
  geom_hline(yintercept = 0) +
  geom_hline(yintercept = -log10(pval_thresh), lty = 2) +
  geom_point(data = wtko_res_shrnklfc %>% filter(sig == TRUE), size = 1)  +
  geom_point(data = wtko_res_shrnklfc %>% filter(sig == FALSE, !is.na(padj)), size = 1, alpha = 0.7) +
  annotate("text", x = 2, y = 100, label = paste0("n = ", wtko_num_deg %>% filter(direction == "up") %>%
                                                    pull(num_deg))) +
  annotate("text", x = -2, y = 100, label = paste0("n = ", wtko_num_deg %>% filter(direction == "down") %>%
                                                     pull(num_deg))) +
  geom_text_repel(data = wtko_res_shrnklfc %>% filter(gene_name == "Firre"), aes(label = gene_name)) +
  theme(legend.position = "none") +
  xlim(-3.5,3.5) +
  ylim(0,125)
ggsave(paste0("figures/firre_ko_wt_volcano_", thresh, ".pdf"), 
       height = 3, width = 3, useDingbats = FALSE)

ggplot(wtko_res_shrnklfc %>% filter(!is.na(padj)), 
       aes(x = log10(baseMean), y = log2FoldChange, color = sig)) +
  geom_hline(yintercept = 0) +
  geom_point(data = wtko_res_shrnklfc %>% filter(sig == TRUE), size = 1)  +
  geom_point(data = wtko_res_shrnklfc %>% filter(sig == FALSE, !is.na(padj)), size = 1, alpha = 0.7) +
  geom_text_repel(data = wtko_res_shrnklfc %>% filter(gene_name == "Firre"), aes(label = gene_name)) +
  theme(legend.position = "none")
ggsave(paste0("figures/firre_ko_wt_ma_", thresh, ".pdf"), 
       height = 3, width = 3, useDingbats = FALSE)
```

